### PR TITLE
Subcategory inheritance

### LINKED ISSUE #67: Category inheritance declared with a property rather than `[[Category:]]` tag
- Create new category `Test` with `[[Has required property::Property:Fizz]]
- Create new category `Test2` with `[[Category:Test]]` and `[[Has required property::Property:Buzz]]

Observe hierarchy viewer doesn't display properties from `Test`:

Image

This appears to be because inheritance is incorrectly determined using a property `Has parent category` rather than the typical `[[Category:]]` declaration on a category page: https://github.com/labki-org/SemanticSchemas/blob/f9763becd31a3a2383e51ca4d1bd69daf81542ef/src/Store/WikiCategoryStore.php#L134

Declaring a category as a subcategory of another using `[[Category:]]` from the subcategory is overwhelmingly canonical and we should not create a new mechanism for declaring category hierarchy - https://www.mediawiki.org/wiki/Help:Categories#Managing_the_category_hierarchy

### PR DESCRIPTION
**Pull request by sneakers-the-rat**
Fix: #67 

In base mediawiki and SMW, subcategories are defined by declaring `[[Category:*]]` on a category page - this is built into the query system, category browser, etc. We should not make another mechanism for declaring subcategories. 

This PR just uses `[[Category:]]` instead of the property. pretty simple. The only caveat is that declaring something a subcategory is no longer done in `Form:Category` since it's not a property, but this should be resolved by a) bundling an explicit `Form:Category`, or b) making a mechanism for declaring non-property forms as can be done with page schemas.

I updated the docs in `docs/` but i didn't touch mentions in `.planning` because that directory makes me nauseous

### CODE REVIEW

**Comment by sneakers-the-rat** [comment]
Yeah i agree it would be nice to keep subcategories in the ui somehow.

I can think of a few options: one likely easy one is we could just have a button on the parent category page thats like "create subcategory", since we wrap the form there, we could inject the subcategory that way.

Another is we inject a special field in the form at display time, i havent checked if page forms has hooks to do this, but if they dont we could make them and pull those upstream.

Another is that page forms has a whole system for declaring form field types, we could likely hook into that to make a "category field"

Its tricky because adding a category has two different meanings for forms when creating categories vs. pages - when creating pages, adding a category means we should add an instance of that category's form to the page's form. When creating categories, we dont want that though, it should just be a list of values. There are the same kind of "level shifting" problems in linkml.

Ultimately i think the strength of this approach is that the schema becomes wikitext, and wikitext is the thing the whole wiki is designed to edit, so i dont think its too terrible to just declare `[[Category:]]` tags in the page. Thats just like a core interface of using the wiki, where declaring individual props and the rest of the schema process is aided by having forms as scaffolding, declaring categories is just a bread and butter wiki basics thing, so i dont feel a strong need to obscure it. But ya the thing we dont wanna do is introduce conflicting mechanisms, partly because declaring categories is such a baseline thing to do.

**Comment by sneakers-the-rat** [comment]
alright, rebased and updated this

File: src/Generator/DisplayStubGenerator.php [hunk 1]
```diff
@@ -67,6 +71,37 @@ public function generateOrUpdateDisplayStub( EffectiveCategoryModel $category ):
 		];
 	}
 
+	/**
+	 * @param CategoryModel $category
+	 * @return string
+	 */
+	public function generateWikitext( CategoryModel $category ): string {
```
Comment (sneakers-the-rat) [inline src/Generator/DisplayStubGenerator.php:78]: made this public - it seems like it should be part of the public interface for this class, since generating wikitext is one of the main things that it does. also most unit tests for this class will be made easier by it being public so they can just operate on the wikitext without needing to hit the database

**Comment by sneakers-the-rat** [comment]
hang on this breaks "generate all categories" and we don't have tests for that, one sec.

File: src/Schema/InheritanceResolver.php [hunk 2]
```diff
@@ -85,6 +86,10 @@ public function getEffectiveCategory( string $categoryName ): EffectiveCategoryM
 		$merged = null;
 
 		foreach ( $linear as $name ) {
+			if ( !array_key_exists( $name, $this->categoryMap ) ) {
```
Comment (sneakers-the-rat) [inline src/Schema/InheritanceResolver.php:89]: declaring a parent category that doesn't exist is a common wiki practice: "declare the category now, come back and make the page later, maybe"

File: src/Schema/InheritanceResolver.php [hunk 3]
```diff
@@ -172,7 +180,11 @@ private function c3Linearization( string $categoryName, array $visiting ): array
 		}
 
 		$category = $this->categoryMap[$categoryName];
-		$parents = $category->getParents();
+		// the SemanticSchemas-managed category is just a marker
+		$parents = array_filter(
+			$category->getParents(),
+			static fn ( $parent ) => $parent != Constants::SEMANTICSCHEMAS_MANAGED_CATEGORY
+		);
```
Comment (sneakers-the-rat) [inline src/Schema/InheritanceResolver.php:187]: made the choice to not strip `SemanticSchemas-managed` from the `parents` array in the category model becasue it's still correct that that is one of its parents, but it's just not handled well by the inheritance resolver specifically. so that leads to some redundance but i think it puts the operation in the right place - this is mostly a hack around #130 without attempting to resolve the full problem there

File: src/Store/WikiCategoryStore.php [hunk 4]
```diff
@@ -111,15 +111,15 @@ public function getAllCategories(): array {
 		$res = $dbr->newSelectQueryBuilder()
 			->select( 'page_title' )
 			->from( 'page' )
-			->where( [ 'page_namespace' => NS_CATEGORY ] )
+			->where( [
+				'page_namespace' => NS_CATEGORY,
+				$dbr->expr( 'page_title', '!=', Constants::SEMANTICSCHEMAS_MANAGED_CATEGORY )
+			] )
```
Comment (sneakers-the-rat) [inline src/Store/WikiCategoryStore.php:117]: extremely mildly faster, generally good to put filtering criterion in the db query so you don't load unnecessary data, even if the thing loaded here is just a single string.

**Comment by daharoni** [comment]
Looks good!
